export const currencyData = {
  'USD': { name: 'US Dollar', symbol: '$', countryCode: 'US' },
  'EUR': { name: 'Euro', symbol: '€', countryCode: 'DE' }, // Using DE for Euro flag
  'GBP': { name: 'British Pound', symbol: '£', countryCode: 'GB' },
  'JPY': { name: 'Japanese Yen', symbol: '¥', countryCode: 'JP' },
  'CAD': { name: 'Canadian Dollar', symbol: 'C$', countryCode: 'CA' },
  'AUD': { name: 'Australian Dollar', symbol: 'A$', countryCode: 'AU' },
  'CHF': { name: 'Swiss Franc', symbol: 'Fr', countryCode: 'CH' },
  'CNY': { name: 'Chinese Yuan', symbol: '¥', countryCode: 'CN' },
  'SEK': { name: 'Swedish Krona', symbol: 'kr', countryCode: 'SE' },
  'NZD': { name: 'New Zealand Dollar', symbol: 'NZ$', countryCode: 'NZ' },
  'MXN': { name: 'Mexican Peso', symbol: '$', countryCode: 'MX' },
  'SGD': { name: 'Singapore Dollar', symbol: 'S$', countryCode: 'SG' },
  'HKD': { name: 'Hong Kong Dollar', symbol: 'HK$', countryCode: 'HK' },
  'NOK': { name: 'Norwegian Krone', symbol: 'kr', countryCode: 'NO' },
  'INR': { name: 'Indian Rupee', symbol: '₹', countryCode: 'IN' },
  'KRW': { name: 'South Korean Won', symbol: '₩', countryCode: 'KR' },
  'RUB': { name: 'Russian Ruble', symbol: '₽', countryCode: 'RU' },
  'BRL': { name: 'Brazilian Real', symbol: 'R$', countryCode: 'BR' },
  'ZAR': { name: 'South African Rand', symbol: 'R', countryCode: 'ZA' },
  'TRY': { name: 'Turkish Lira', symbol: '₺', countryCode: 'TR' },
  'PLN': { name: 'Polish Zloty', symbol: 'zł', countryCode: 'PL' },
  'DKK': { name: 'Danish Krone', symbol: 'kr', countryCode: 'DK' },
  'CZK': { name: 'Czech Koruna', symbol: 'Kč', countryCode: 'CZ' },
  'HUF': { name: 'Hungarian Forint', symbol: 'Ft', countryCode: 'HU' },
  'ILS': { name: 'Israeli Shekel', symbol: '₪', countryCode: 'IL' },
  'CLP': { name: 'Chilean Peso', symbol: '$', countryCode: 'CL' },
  'PHP': { name: 'Philippine Peso', symbol: '₱', countryCode: 'PH' },
  'AED': { name: 'UAE Dirham', symbol: 'د.إ', countryCode: 'AE' },
  'COP': { name: 'Colombian Peso', symbol: '$', countryCode: 'CO' },
  'SAR': { name: 'Saudi Riyal', symbol: '﷼', countryCode: 'SA' },
  'MYR': { name: 'Malaysian Ringgit', symbol: 'RM', countryCode: 'MY' },
  'RON': { name: 'Romanian Leu', symbol: 'lei', countryCode: 'RO' },
  'BGN': { name: 'Bulgarian Lev', symbol: 'лв', countryCode: 'BG' },
  'HRK': { name: 'Croatian Kuna', symbol: 'kn', countryCode: 'HR' },
  'ISK': { name: 'Icelandic Krona', symbol: 'kr', countryCode: 'IS' },
  'THB': { name: 'Thai Baht', symbol: '฿', countryCode: 'TH' },
  'EGP': { name: 'Egyptian Pound', symbol: '£', countryCode: 'EG' },
  'PKR': { name: 'Pakistani Rupee', symbol: '₨', countryCode: 'PK' },
  'QAR': { name: 'Qatari Riyal', symbol: '﷼', countryCode: 'QA' },
  'KWD': { name: 'Kuwaiti Dinar', symbol: 'د.ك', countryCode: 'KW' },
  'BHD': { name: 'Bahraini Dinar', symbol: '.د.ب', countryCode: 'BH' },
  'OMR': { name: 'Omani Rial', symbol: '﷼', countryCode: 'OM' },
  'JOD': { name: 'Jordanian Dinar', symbol: 'د.ا', countryCode: 'JO' },
  'LBP': { name: 'Lebanese Pound', symbol: '£', countryCode: 'LB' },
  'VND': { name: 'Vietnamese Dong', symbol: '₫', countryCode: 'VN' },
  'IDR': { name: 'Indonesian Rupiah', symbol: 'Rp', countryCode: 'ID' },
  'TWD': { name: 'Taiwan Dollar', symbol: 'NT$', countryCode: 'TW' },
  'UAH': { name: 'Ukrainian Hryvnia', symbol: '₴', countryCode: 'UA' },
  'MAD': { name: 'Moroccan Dirham', symbol: 'د.م.', countryCode: 'MA' },
  'TND': { name: 'Tunisian Dinar', symbol: 'د.ت', countryCode: 'TN' },
  'DZD': { name: 'Algerian Dinar', symbol: 'د.ج', countryCode: 'DZ' },
  'LYD': { name: 'Libyan Dinar', symbol: 'ل.د', countryCode: 'LY' },
  'ETB': { name: 'Ethiopian Birr', symbol: 'Br', countryCode: 'ET' },
  'KES': { name: 'Kenyan Shilling', symbol: 'KSh', countryCode: 'KE' },
  'NGN': { name: 'Nigerian Naira', symbol: '₦', countryCode: 'NG' },
  'GHS': { name: 'Ghanaian Cedi', symbol: '₵', countryCode: 'GH' },
  'XAF': { name: 'Central African CFA Franc', symbol: 'FCFA', countryCode: 'CM' },
  'XOF': { name: 'West African CFA Franc', symbol: 'CFA', countryCode: 'SN' },
  'UGX': { name: 'Ugandan Shilling', symbol: 'USh', countryCode: 'UG' },
  'TZS': { name: 'Tanzanian Shilling', symbol: 'TSh', countryCode: 'TZ' },
  'ZMW': { name: 'Zambian Kwacha', symbol: 'ZK', countryCode: 'ZM' },
  'BWP': { name: 'Botswanan Pula', symbol: 'P', countryCode: 'BW' },
  'NAD': { name: 'Namibian Dollar', symbol: 'N$', countryCode: 'NA' },
  'SZL': { name: 'Swazi Lilangeni', symbol: 'L', countryCode: 'SZ' },
  'LSL': { name: 'Lesotho Loti', symbol: 'M', countryCode: 'LS' },
  'MGA': { name: 'Malagasy Ariary', symbol: 'Ar', countryCode: 'MG' },
  'MUR': { name: 'Mauritian Rupee', symbol: '₨', countryCode: 'MU' },
  'SCR': { name: 'Seychellois Rupee', symbol: '₨', countryCode: 'SC' },
  'MVR': { name: 'Maldivian Rufiyaa', symbol: '.ރ', countryCode: 'MV' },
  'LKR': { name: 'Sri Lankan Rupee', symbol: '₨', countryCode: 'LK' },
  'NPR': { name: 'Nepalese Rupee', symbol: '₨', countryCode: 'NP' },
  'BTN': { name: 'Bhutanese Ngultrum', symbol: 'Nu.', countryCode: 'BT' },
  'BDT': { name: 'Bangladeshi Taka', symbol: '৳', countryCode: 'BD' },
  'MMK': { name: 'Myanmar Kyat', symbol: 'Ks', countryCode: 'MM' },
  'LAK': { name: 'Lao Kip', symbol: '₭', countryCode: 'LA' },
  'KHR': { name: 'Cambodian Riel', symbol: '៛', countryCode: 'KH' },
  'MNT': { name: 'Mongolian Tugrik', symbol: '₮', countryCode: 'MN' },
  'KZT': { name: 'Kazakhstani Tenge', symbol: '₸', countryCode: 'KZ' },
  'UZS': { name: 'Uzbekistani Som', symbol: 'лв', countryCode: 'UZ' },
  'KGS': { name: 'Kyrgystani Som', symbol: 'лв', countryCode: 'KG' },
  'TJS': { name: 'Tajikistani Somoni', symbol: 'SM', countryCode: 'TJ' },
  'TMT': { name: 'Turkmenistani Manat', symbol: 'T', countryCode: 'TM' },
  'AFN': { name: 'Afghan Afghani', symbol: '؋', countryCode: 'AF' },
  'IRR': { name: 'Iranian Rial', symbol: '﷼', countryCode: 'IR' },
  'IQD': { name: 'Iraqi Dinar', symbol: 'ع.د', countryCode: 'IQ' },
  'SYP': { name: 'Syrian Pound', symbol: '£', countryCode: 'SY' },
  'YER': { name: 'Yemeni Rial', symbol: '﷼', countryCode: 'YE' },
  'GEL': { name: 'Georgian Lari', symbol: '₾', countryCode: 'GE' },
  'AMD': { name: 'Armenian Dram', symbol: '֏', countryCode: 'AM' },
  'AZN': { name: 'Azerbaijani Manat', symbol: '₼', countryCode: 'AZ' },
  'BYN': { name: 'Belarusian Ruble', symbol: 'Br', countryCode: 'BY' },
  'MDL': { name: 'Moldovan Leu', symbol: 'L', countryCode: 'MD' },
  'RSD': { name: 'Serbian Dinar', symbol: 'Дин.', countryCode: 'RS' },
  'MKD': { name: 'Macedonian Denar', symbol: 'ден', countryCode: 'MK' },
  'ALL': { name: 'Albanian Lek', symbol: 'L', countryCode: 'AL' },
  'BAM': { name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', countryCode: 'BA' },
  'EUR': { name: 'Euro', symbol: '€', countryCode: 'DE' }
}